version: 0.2

env:
  variables:
    node_env: "ci"
    port: "3000"

language: node_js

node_js: 
  - "8"

dist: trusty

services:
  - mongodb
  - redis-server

env:
  variables:
    NODE_ENV: $node_env
    PORT: $port

cache:
  paths:
    - node_modules
    - client/node_modules

install:
  commands:
    - npm install
    - npm run build

script:
  - nohup npm run start &
  - sleep 4
  - npm run test