version: 0.2

env:
  variables:
    node_env: "ci"
    port: "3000"

phases:
  install:
    runtime-versions:
      nodejs: 12
    build:
      commands:
        - echo Entered the install phase
        - npm install
        - echo Entered the build phase
        - npm run build
        - echo Entered the testing phase
        - npm run test

  env:
    variables:
      NODE_ENV: $node_env
      PORT: $port

  cache:
    paths:
      - node_modules
      - client/node_modules  

  build:
    - nohup npm run start &
    - sleep 4
    - npm run test